### ISSUE TITLE
Create new calendar event modal

### ISSUE THREAD

**Issue by jpugmire** [elizabethbillings93/familycalendar#10]
Somebody needs to create the HTML elements which will be conditionally rendered when the user wants to add a new calendar event.
This modal will be a small box in the center of the screen, with two buttons, create and cancel.
A form in the modal will have a few fields:
eventName
eventDate
eventCategory
eventLocation (will need to determine which api we are using for the location)

The 'create' button will use the provided data to create an object that is then used to render an HTML element on the page.
The 'cancel' button will close the modal and clear the data in the form fields, so that when it is opened again they remain blank.

**Comment by jpugmire** [comment]
I'm happy to do the scripting work for this. We will need to have someone assigned to the HTML that renders the modal.
The way this works is we append the HTML you'll write with javascript, so practice adding it hardcoded at first to see if it renders correctly.

**Comment by jimbolikesgithub** [comment]
Created and added a calendar event modal which includes the name, date, category, and location of whatever the user decides to input.
