### ISSUE TITLE
event info modal HTML

### ISSUE THREAD

**Issue by jpugmire** [elizabethbillings93/familycalendar#12]
this will represent the work for the modal that is rendered when a user clicks on an event.
Again, we will append HTML to the page so a good way to practice this before the scripting is done is simply to hardcode the HTML and make sure it all looks good.
This modal will need to have two buttons, a space at the top for the title of the event and category, then a pane below for the google maps api, and a pane below that for the weather api. a bottom bar will contain the two buttons, 'edit' and 'close'

**Comment by jimbolikesgithub** [comment]
Added the second event modal, this one, however, holds appended HTML elements with data from both a weather API and a map API.
